name: 03 - Workflow Runners
on: 
    workflow_dispatch:

jobs:            
    self-hosted-echo:
        runs-on: self-hosted
        steps:
            - name: Show OS
              run: |
                echo "OS: ${{ runner.os }}"            
